name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - refactor

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone doxygen-awesome
        run: |
          git clone https://github.com/jothepro/doxygen-awesome-css
        
      - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
